### PR TITLE
Feature/win_get_parent_id

### PR DESCRIPTION
**Pull request by SheenArtem**
Hi,

This branch is forked from 0.14.0.

I add some stuff to get the parent's id for each hid_device_info.

Since I've met a problem that more than one USB composite device with multiple HID interface using same VID_PID.

And I need to do operation on each USB device.

Thanks for this library saving lots of time for me.

### CODE REVIEW

**Comment by SheenArtem** [comment]
Got new idea to complete this feature.

**Comment by Youw** [comment]
You should be able to get a parent from `hid_winapi_get_container_id` w/o any modifications to HIDAPI itself.

**Comment by SheenArtem** [comment]
image

What I want is something like the "Parent Physcal Addr" in the image.

So that I can distinguish two devices with same VID PID.

Maybe there's another way to do this.

So, if it's acceptable, I'll make a PR again.

I'll make my modification at [feature](https://github.com/SheenArtem/hidapi/tree/feature/win-get-parent-id) 

Thank you

**Comment by Youw** [comment]
> So that I can distinguish two devices with same VID PID.

For that sole purpose a `path` should be sufficient - different physical devices always have different `path`s.

**Comment by SheenArtem** [comment]
Thanks!!  I 'm don't really have any idea about the Windows USB.

So, I can use the number `7` between `Col01#` and the `&`, to distinguish if the HID devices are from the same physical device?

Because I don't know if the number is random generated and meaningful.

`\\?\HID#VID_1DE1&PID_F201&MI_01&Col02#8&1c25a3a4&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}`
`\\?\HID#VID_1DE1&PID_F201&MI_01&Col01#8&1c25a3a4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}`
`\\?\HID#VID_1DE1&PID_F201&MI_00&Col02#8&33e92fe9&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}`
`\\?\HID#VID_1DE1&PID_F201&MI_00&Col01#8&33e92fe9&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}`
`\\?\HID#VID_1DE1&PID_F201&MI_00&Col02#7&18634b4b&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}`
`\\?\HID#VID_1DE1&PID_F201&MI_00&Col01#7&18634b4b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}`
`\\?\HID#VID_1DE1&PID_F201&MI_01&Col02#7&5332f0d&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}`
`\\?\HID#VID_1DE1&PID_F201&MI_01&Col01#7&5332f0d&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}`

**Comment by Youw** [comment]
That you should check with MS documentation.
As far as HIDAPI conserns - different `path`s (as an entire C string) means different devices, and you should not attempt to parse it unless you absolutely know how to do it and using WinAPI + documentation that specificly allows it.

**Pull request closed without merging**
