### PR TITLE
Fixed Visual C++ warning C4214

### PR DESCRIPTION
**Pull request by slouken**

### CODE REVIEW

**Comment by Youw** [comment]
What is the original warning?
In theory I might understand why change ULONG to UINT, but BOOLEAN to UINT is not as traight-forward.

That struct has to be 100% ABI stable. It is reversed-engineered, based on some pieces found online.

Please see that the CI build is failing.

I'd consider explicitly supressing some warnings, instead of changing types as suggested in this PR.

**Comment by slouken** [comment]
Investigating test failures...

**Comment by slouken** [comment]
Okay, I'll make that change instead. I think the change of BOOLEAN to UINT may be incorrect here.

**Review by Youw — APPROVED** [review]

**Comment by Youw** [comment]
thanks

**Pull request merged**
