### PR TITLE
macOS: Check for macOS 10.10 using kCFCoreFoundationVersionNumber instead of AppKit

### PR DESCRIPTION
**Pull request by mrpippy**
Fixes: #587

### CODE REVIEW

**Comment by Youw** [comment]
This looks perfect.
@nguyen-phillip can you confirm this fixes the issue in your environment?

**Comment by nguyen-phillip** [comment]
Yes, this should work -- the issue only manifests when linked against AppKit. Thanks!

**Comment by Youw** [comment]
> should work

Would you be able to actually run and check?
Thanks.

**Comment by nguyen-phillip** [comment]
We've patched out this version check entirely as we don't need to support macOS predating 10.10. However the minimal repro code for the (still open) Apple bug only has problems when AppKit is linked in. CoreFoundation and IOKit are fine.

**Review by Youw — APPROVED** [review]
I wasn't able to reproduce the original #587 with current master. Maybe because I'm using M2 mac machine. Thus I cannot confirm if it really fixes the original issue or not.

@mrpippy can you confirm that you had the original issue reproduced locally and not reproducible after this change?

In any case - this make one dependency less compared to "before" which is a great thing on its own.

**Pull request merged**
