### PR TITLE
add CMake build system

### PR DESCRIPTION
**Pull request by Youw**
Resolves: #12
Closes: #220

### CODE REVIEW

**Comment by mcuee** [comment]
Seems to work fine under Windows 10 and VS2019. I just tried to use CMake-GUI and VS2019.

```
Rebuild started...
1>------ Rebuild All started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Checking Build System
2>------ Rebuild All started: Project: hidapi_winapi, Configuration: Debug x64 ------
2>Building Custom Rule C:/work/hid/hidapi_cmake/windows/CMakeLists.txt
2>hid.c
2>   Creating library C:/work/hid/hidapi_cmake/build/src/windows/Debug/hidapi.lib and object C:/work/hid/hidapi_cmake/build/src/windows/Debug/hidapi.exp
2>hidapi_winapi.vcxproj -> C:\work\hid\hidapi_cmake\build\src\windows\Debug\hidapi.dll
3>------ Rebuild All started: Project: hidtest, Configuration: Debug x64 ------
3>Building Custom Rule C:/work/hid/hidapi_cmake/hidtest/CMakeLists.txt
3>test.c
3>hidtest.vcxproj -> C:\work\hid\hidapi_cmake\build\hidtest\Debug\hidtest.exe
4>------ Rebuild All started: Project: ALL_BUILD, Configuration: Debug x64 ------
4>Building Custom Rule C:/work/hid/hidapi_cmake/CMakeLists.txt
5>------ Skipped Rebuild All: Project: INSTALL, Configuration: Debug x64 ------
5>Project not selected to build for this solution configuration 
========== Rebuild All: 4 succeeded, 0 failed, 1 skipped ==========
```

**Comment by mcuee** [comment]
The output directory is a bit different from the current VS solution file though.

```
Rebuild started...
1>------ Rebuild All started: Project: hidapi, Configuration: Debug x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(513,5): warning MSB8028: The intermediate directory (x64\Debug\) contains files shared from another project (hidtest.vcxproj).  This can lead to incorrect clean and rebuild behavior.
1>hid.c
1>   Creating library C:\work\hid\hidapi_cmake\windows\x64\Debug\hidapi.lib and object C:\work\hid\hidapi_cmake\windows\x64\Debug\hidapi.exp
1>hidapi.vcxproj -> C:\work\hid\hidapi_cmake\windows\x64\Debug\hidapi.dll
1>Done building project "hidapi.vcxproj".
2>------ Rebuild All started: Project: hidtest, Configuration: Debug x64 ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(513,5): warning MSB8028: The intermediate directory (x64\Debug\) contains files shared from another project (hidapi.vcxproj).  This can lead to incorrect clean and rebuild behavior.
2>test.c
2>hidtest.vcxproj -> C:\work\hid\hidapi_cmake\windows\x64\Debug\hidtest.exe
2>Done building project "hidtest.vcxproj".
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

```

**Comment by mcuee** [comment]
There is a warning under MSYS2 MinGW-w64.

```

XFCHEN@1TV4433 MINGW64 /c/work/hid/hidapi_cmake/build_mingw64
$ cmake -G "MinGW Makefiles" ..
-- The C compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- hidapi: v0.10.1
-- Configuring done
-- Generating done
-- Build files have been written to: C:/work/hid/hidapi_cmake/build_mingw64

XFCHEN@1TV4433 MINGW64 /c/work/hid/hidapi_cmake/build_mingw64
$ make
Microsoft Windows [Version 10.0.19041.985]
(c) Microsoft Corporation. All rights reserved.

C:\work\hid\hidapi_cmake\build_mingw64>mingw32-make
mingw32-make[1]: Entering directory 'C:/work/hid/hidapi_cmake/build_mingw64'
mingw32-make[2]: Entering directory 'C:/work/hid/hidapi_cmake/build_mingw64'
mingw32-make[3]: Entering directory 'C:/work/hid/hidapi_cmake/build_mingw64'
mingw32-make[3]: Leaving directory 'C:/work/hid/hidapi_cmake/build_mingw64'
mingw32-make[3]: Entering directory 'C:/work/hid/hidapi_cmake/build_mingw64'
[ 25%] Building C object src/windows/CMakeFiles/hidapi_winapi.dir/hid.c.obj
C:\work\hid\hidapi_cmake\windows\hid.c: In function 'hid_enumerate':
C:\work\hid\hidapi_cmake\windows\hid.c:459:5: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
  459 |     strncpy(cur_dev->path, str, len+1);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\work\hid\hidapi_cmake\windows\hid.c:457:11: note: length computed here
  457 |     len = strlen(str);
      |           ^~~~~~~~~~~
[ 50%] Linking C shared library libhidapi.dll
mingw32-make[3]: Leaving directory 'C:/work/hid/hidapi_cmake/build_mingw64'
[ 50%] Built target hidapi_winapi
mingw32-make[3]: Entering directory 'C:/work/hid/hidapi_cmake/build_mingw64'
mingw32-make[3]: Leaving directory 'C:/work/hid/hidapi_cmake/build_mingw64'
mingw32-make[3]: Entering directory 'C:/work/hid/hidapi_cmake/build_mingw64'
[ 75%] Building C object hidtest/CMakeFiles/hidtest.dir/test.c.obj
[100%] Linking C executable hidtest.exe
mingw32-make[3]: Leaving directory 'C:/work/hid/hidapi_cmake/build_mingw64'
[100%] Built target hidtest
mingw32-make[2]: Leaving directory 'C:/work/hid/hidapi_cmake/build_mingw64'
mingw32-make[1]: Leaving directory 'C:/work/hid/hidapi_cmake/build_mingw64'
```

**Comment by mcuee** [comment]
No issues under Linux (Raspberry Pi 400 running 64 bit Ubuntu ARM Linux)

**Comment by mcuee** [comment]
Looking at the VS2019 build, it seems to me the directory is a bit strange.

```
Rebuild started...
1>------ Rebuild All started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>Checking Build System
2>------ Rebuild All started: Project: hidapi_winapi, Configuration: Release x64 ------
2>Building Custom Rule C:/work/hid/hidapi_cmake/windows/CMakeLists.txt
2>hid.c
2>   Creating library C:/work/hid/hidapi_cmake/build_vs2019/src/windows/Release/hidapi.lib and object C:/work/hid/hidapi_cmake/build_vs2019/src/windows/Release/hidapi.exp
2>hidapi_winapi.vcxproj -> C:\work\hid\hidapi_cmake\build_vs2019\src\windows\Release\hidapi.dll
3>------ Rebuild All started: Project: hidtest, Configuration: Release x64 ------
3>Building Custom Rule C:/work/hid/hidapi_cmake/hidtest/CMakeLists.txt
3>test.c
3>hidtest.vcxproj -> C:\work\hid\hidapi_cmake\build_vs2019\hidtest\Release\hidtest.exe
4>------ Rebuild All started: Project: ALL_BUILD, Configuration: Release x64 ------
4>Building Custom Rule C:/work/hid/hidapi_cmake/CMakeLists.txt
5>------ Skipped Rebuild All: Project: INSTALL, Configuration: Release x64 ------
5>Project not selected to build for this solution configuration 
========== Rebuild All: 4 succeeded, 0 failed, 1 skipped ==========


C:\work\hid\hidapi_cmake\build_vs2019 [cmake-support-to-master ≡ +3 ~0 -0 !]> ls

    Directory: C:\work\hid\hidapi_cmake\build_vs2019

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           6/22/2021  3:26 PM                CMakeFiles
d----           6/22/2021  3:24 PM                export_generated
d----           6/22/2021  3:25 PM                hidtest
d----           6/22/2021  3:24 PM                src
d----           6/22/2021  3:07 PM                x64
-a---           6/22/2021  3:24 PM          16017 ALL_BUILD.vcxproj
-a---           6/22/2021  2:55 PM            279 ALL_BUILD.vcxproj.filters
-a---           6/22/2021  3:24 PM           1696 cmake_install.cmake
-a---           6/22/2021  3:24 PM          16444 CMakeCache.txt
-a---           6/22/2021  3:24 PM           5273 hidapi.sln
-a---           6/22/2021  2:55 PM          11897 INSTALL.vcxproj
-a---           6/22/2021  2:55 PM            528 INSTALL.vcxproj.filters
-a---           6/22/2021  3:24 PM          18560 ZERO_CHECK.vcxproj
-a---           6/22/2021  2:55 PM            529 ZERO_CHECK.vcxproj.filters


C:\work\hid\hidapi_cmake\build_vs2019 [cmake-support-to-master ≡ +3 ~0 -0 !]> ls .\x64\Release\

    Directory: C:\work\hid\hidapi_cmake\build_vs2019\x64\Release

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           6/22/2021  3:26 PM                ALL_BUILD
d----           6/22/2021  3:26 PM                ZERO_CHECK

```

By right, the files should not be under src/windows/Release directory but rather x64/Release directory.

**Comment by Youw** [comment]
> There is a warning under MSYS2 MinGW-w64.

I wounder if we have that warning when built with Autotools (if I had to guess - it is there too).
In any case, we better fix the warning in the source code, i.e. I won't tweak the build system to hide the warning.

> Looking at the VS2019 build, it seems to me the directory is a bit strange.

That is the default behavior of CMake - by default it generates under the build tree same directory structure as the source tree, and places each library/executable under the the directory, which defines it in the source.

In any case, by CMake ideology - no one should try to expect/get specific artifacts from whithin the build tree, but rather run `install` target and get everything you need from install diretrory (it doesn't have to be a /usr/local - it could be any diretory on the filesystem).

**Comment by mcuee** [comment]
@Youw 
Yes the warning with windows\hid.c is there with Autotools as well. And yes it should be fixed in the source code.

**Review by mcuee — APPROVED** [review]

**Comment by OgreTransporter** [comment]
CMake support is a good improvement. If you want, you can copy the documentation with doxygen from my version (https://github.com/OgreTransporter/hidapi). Alternatively I can create a PR after CMake has been merged.

**Comment by Be-ing** [comment]
What is left to do here?

**Comment by Youw** [comment]
Time to have it merged.

**Comment by Youw** [comment]
> copy the documentation with doxygen from my version

There is already a markdown documentation, unless I missunderstood your suggestion.

**Comment by Be-ing** [comment]
Thank you @Youw!

**Comment by Youw** [comment]
I really want to thank the community for helping making this possible.
Many constructive comments and suggestions (mostly under #220) did made the implementation better than was initialy developed by me.
I definitely will be using HIDAPI CMake build system as an example of community effort and a very convinient (from usage perspective) implementation.

**Pull request merged**
