### PR TITLE
drop support of macOS 10.5 and earlier

### LINKED ISSUE #119: macOS: location of IOKit.framework
Hi there,

according to

https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/OSX_Technology_Overview/SystemFrameworks/SystemFrameworks.html

IOKit.framework is located at "/System/Library/Frameworks/", but mac/hid.c:hidapi_IOHIDDeviceGetService() tries to find it at "/System/Library/".

```
--- a/hidapi/mac/hid.c
+++ b/hidapi/mac/hid.c
@@ -305,7 +305,7 @@ static io_service_t hidapi_IOHIDDeviceGe
 	 * and the fallback method will be used.
 	 */
 	if (iokit_framework == NULL) {
-		iokit_framework = dlopen("/System/Library/IOKit.framework/IOKit", RTLD_LAZY);
+		iokit_framework = dlopen("/System/Library/Frameworks/IOKit.framework/IOKit", RTLD_LAZY);
 
 		if (iokit_framework != NULL)
 			dynamic_IOHIDDeviceGetService = (dynamic_IOHIDDeviceGetService_t) dlsym(iokit_framework, "IOHIDDeviceGetService");
```

Regards,
Dennis

### PR DESCRIPTION
**Pull request by Youw**
IOHIDDeviceGetService is available since macOS 10.6
dropping an old workaround makes the implementation simpler

Similar to #39.

Fixes #119
Closes #120

### CODE REVIEW

**Comment by Youw** [comment]
Any votes against?

**Comment by z3ntu** [comment]
I'm fine personally with 10.6.8+ being supported. But there are definitely still people with macOS versions lower than 10.6 that are interested in software on those devices (see e.g. https://github.com/mistydemeo/tigerbrew - this is not just PPC but now everything < 10.9 or something because homebrew dropped support for macOS versions lower than that)

**Comment by Youw** [comment]
In this particular example, tigerbrew Formula is still using signal11's copy of the repo: (current master) https://github.com/mistydemeo/tigerbrew/blob/4cce1912cc68a15a0d47f5744b489ae68dfe94fa/Library/Formula/hidapi.rb

**Comment by Youw** [comment]
Maybe it is time, to finally fine a new release, and it will be a last release, that supports macOS 10.5.

**Comment by mcuee** [comment]
@Youw Please merge this as well. Thanks.

**Pull request merged**
