### PR TITLE
libusb: allow hidapi to be configured without using iconv

### PR DESCRIPTION
**Pull request by wet34t**

### CODE REVIEW

**Comment by Youw** [comment]
additionally would be great to have auto-tools option to enable this

**Comment by wet34t** [comment]
Basically, the idea is to allow users to configure hidapi without using iconv, as icvon may have dependencies that may not be supported

**Comment by z3ntu** [comment]
What's the use case for this patch? As far as I know, iconv is implemented directly in glibc and for non-glibc libcs, there's GNU libiconv which also apparently doesn't have any dependencies other than the C library.

**Comment by wet34t** [comment]
iconv depends on /usr/lib[64]/gconv, which usually is part of glibc, but may not always be the case.

**Comment by Youw** [comment]
I see no issues accepting this as is

**Comment by z3ntu** [comment]
I still haven't seen an exact reason like "On X distro iconv isn't available and as such hidapi must be built without it" or something like that.

To my knowledge, glibc has iconv built in, musl as well. For other libc's you can install GNU libiconv and use that instead of the built-in-to-the-C-library libiconv.

**Comment by Youw** [comment]
@wet34t, did you hit one of the cases described by @z3ntu?

**Comment by wet34t** [comment]
I'm experiencing similar issues as described here:
https://stackoverflow.com/questions/9560671/weird-iconv-open-behavior-in-linux

**Comment by Youw** [comment]
I see no issues having this as is for community convenience

**Pull request merged**
