### PR TITLE
linux: Drop workaround for kernel < 2.6.34

### PR DESCRIPTION
**Pull request by z3ntu**
Also drop HIDIOC* definitions as they are present since kernel 2.6.39.

### CODE REVIEW

**Comment by Youw** [comment]
where do we define minimum supported kernel?

**Comment by Youw** [comment]
I still think it worth adding at least README notice. Would you?

**Comment by z3ntu** [comment]
If you're willing to test hidapi on e.g. kernel 2.6.39 then sure; but other than downloading the oldest supported CentOS version I wouldn't even know how to get a VM running kernel 2.6.39

**Comment by Youw** [comment]
Hm, good point - don't want to check/make any assures on support.
What about:
"Don't try to compile with Kernel older than 2.6.39 - it won't".

As usual, there will be that one person, who will try and open a bug.

**Comment by z3ntu** [comment]
> As usual, there will be that one person, who will try and open a bug.

I'd say, if someone opens a bug report for that, we can add it to the readme :wink:

**Pull request merged**
