### PR TITLE
v0.13.0 for new API function

### PR DESCRIPTION
**Pull request by Youw**

### CODE REVIEW

**Comment by Megamouse** [comment]
I think you forgot to add a tag to the commit

**Comment by Youw** [comment]
0.13 is not in release yet
as for now - it is latest master

**Comment by mcuee** [comment]
@Youw 

Just wondering anything you want to merge before 0.13.0 release. Thanks. 

Probably it is good to merge a few of mature PRs and then release 0.13.0 (or maybe RC1 first).
* #467 

Do you want to finish working on #485 and then call the 0.13.0 release? I think it can be later if you do not have time.
* #485

**Comment by Youw** [comment]
Excuse me for not getting to HIDAPI for a while. As usual, been busy with too many things at once.

Merging #467 into `get-description` branch is a good idea. I has been there for a while and I haven't heard a lot of feedback about for a while. I think we'll get it into master before 0.14 release.

As for #485 - it is already an improvement for 0.13, even if not a 100% finished, so I probably get it merged, even if I won't find time to make all things I've planed.

---
As for 0.13 release itself - I did said it would be great to have it released before Christmas, and it is a shame I couldn't plan my personal time to get it done.
No strong promices yet, but December 30 is a likely the date when I'll have it released.

**Comment by mcuee** [comment]
@Youw 

I totally agree with your plan. Take your time.

**Pull request merged**
