### PR TITLE
hidtest: don't use a C++ source file, since it's pure C

### PR DESCRIPTION
**Pull request by z3ntu**
This allows to build the test program with toolchains that don't have
C++ support.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>

Originally https://github.com/signal11/hidapi/pull/249

### CODE REVIEW

**Comment by z3ntu** [comment]
The cpp file is still referenced in 
```
windows/hidtest.vcproj:                         RelativePath="..\hidtest\hidtest.cpp"
```
This should be updated as well I think?

**Comment by z3ntu** [comment]
I can't 100% verify that the Windows version builds fine because of an additional commit needed for appveyor (vs2015); but in general it still builds fine: https://ci.appveyor.com/project/z3ntu/hidapi/builds/25520538/job/64xs7pjqx1mhas4q

**Comment by Youw** [comment]
> additional commit needed for appveyor (vs2015)

we can fix any possible issues when it comes to it
so far looks good

**Comment by Youw** [comment]
compiles on Windows with automatic conversion of `.sln` by MSVC2017

**Pull request merged**
