### PR TITLE
Add continuous integration config

### PR DESCRIPTION
**Pull request by z3ntu**
This PR is for the platforms listed at #6 except Windows (msbuild & cygwin) as that needs an upgrade of the VS project to a newer version; see #12 

See also #15 

This would need configuration of https://dispatch.sr.ht and https://travis-ci.com/ on this repo.

### CODE REVIEW

**Comment by Youw** [comment]
I'd suggest to build an `install` target, to check by CI that it is correctly configured too.

**Comment by z3ntu** [comment]
@Youw What should be checked there? I would think of passing autotools `--prefix=/myprefix`, then running `make DESTDIR=mydir install` and checking if `./mydir/myprefix/lib/libhidapi-hidraw.so` exists or something like that

**Comment by Youw** [comment]
> --prefix=/myprefix

Yeap.

> What should be checked there?

As a sanity test - just to make sure that `make install` returns "success". Checking that `*.so` exists - may be a good check, but I wouldn't say it is mandatory. That is up to you.

Also, if we want to see artifacts at some point - artifacts from `install` target is what need to be gathered.

**Comment by z3ntu** [comment]
Artifacts for *nix builds are unnecessary imo. I'll add the make install calls.

**Comment by z3ntu** [comment]
Make install commands are now added to all CIs.

**Comment by Qbicz** [comment]
@z3ntu should I integrate Travis and https://dispatch.sr.ht with this repo before we merge it?

**Comment by z3ntu** [comment]
Yeah. And I think both CIs don't attempt to build something if the config files aren't present

**Comment by Qbicz** [comment]
@LudovicRousseau can you check if you have received any email regarding Travis CI or Sourcehut (sr.ht) access to this repo? When I want authorize the CI, it says I cannot authorize it for the organization libusb and that email has been sent to the owner.

**Comment by LudovicRousseau** [comment]
@Qbicz yes, I got an access request.

> Review third-party application access request
> Granting access will give this application the ability to request access to private data in the libusb organization. 

I don't know why Sourcehut would need to access the **private** data of the libusb organization.

What is Sourcehut supposed to do?

I granted access to travis-ci.com. travis-ci.org already had access.

**Comment by z3ntu** [comment]
Comment from https://todo.sr.ht/~sircmpwn/dispatch.sr.ht/22:

> We need those permissions to install the webhook which notifies sr.ht of pull requests et al. There are no more conservative permissions for this.

But there's also a ticket open (but not in progress) for not granting those permissions and setting up the webhook manually: https://todo.sr.ht/~sircmpwn/dispatch.sr.ht/25

**Comment by LudovicRousseau** [comment]
Approved now.

**Comment by Qbicz** [comment]
Added hooks for dispatch.sr.ht and Travis.

**Pull request merged**
