### PR TITLE
[Untestedcode] Report Descriptor code for MAC

### PR DESCRIPTION
**Pull request by JoergAtGithub**
I coded this offline, because I don't have access to a MAC system.

### CODE REVIEW

**Comment by Youw** [comment]
I have Mac/Linux machines, so I can check/implement those withing few days.

**Comment by JoergAtGithub** [comment]
That would be great, I just found this code during my research for the windows implementation and thought it might help to have it as reference.

**Comment by Youw** [comment]
It won't harm.
I also did some investigation of my own in this direction, and I find implementation for each platform (except Windows) to be straight-forward.

**Comment by mcuee** [comment]
@JoergAtGithub I will test this as well on my Mac Mini M1 over the weekend.

**Comment by mcuee** [comment]
@JoergAtGithub Just wondering if you have anything for Linux as well? Thanks. I usually use my Raspberry Pi 400 for Linux testing.

**Comment by mcuee** [comment]
@JoergAtGithub Hmm, this one does not seem to have any test code or debug output. Not sure what is the best way to test it.

But for macOS, maybe this one can be a good start.
https://github.com/todbot/mac-hid-dump/blob/main/mac-hid-dump.c

**Comment by JoergAtGithub** [comment]
Superseeded by #303

**Pull request closed without merging**
