### PR TITLE
podspec: include darwin-specific header

### PR DESCRIPTION
**Pull request by Youw**

### CODE REVIEW

**Comment by Youw** [comment]
@vitalys can you help me check if this will work as expected? (Can we actually check it w/o firing the actual new build on podspec?)

**Comment by vitalys** [comment]
@Youw I'm really sorry, I missed your comment. 
I have a question: is `hidapi_darwin.h` public header or for internal usage only?

**Comment by Youw** [comment]
Yes, that is a new public header for Darwin platform only.

**Comment by Youw** [comment]
Thanks

**Review by vitalys — APPROVED** [review]
Looks good to me

**Review by vitalys — APPROVED** [review]

**Comment by JoergAtGithub** [comment]
> As for testing, you can use `pod lib lint`, but you have to move `hidapi.podspec` to the root folder and fix `VERSIONS` file path.

Would it make sense to execute this linter in GitHub Actions?

**Comment by Youw** [comment]
No, I don't think that's required.
Maybe as part of the [automated release script](https://github.com/libusb/hidapi/issues/366), which doesn't exist yet.

**Comment by vitalys** [comment]
@Youw are you going to merge this PR? I'd like to release v0.12.0 via cocoapods

**Pull request merged**
